version: '2.2'
services:
  api-python:
    build:
      context: ./ranking_system
      dockerfile: Dockerfile
    command: python /codebase/api_server.py
    ports:
      - 5000:5000
  api-js:
    build:
      context: ./vk_interaction_obj_rec
      dockerfile: Dockerfile
  mongo-db:
    image: mongo:4.0.6
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
    - 27017:27017