---
- name: Ensure application directory exists
  action: file path={{ app_dir }} state=directory

- name: Copy docker-compose
  copy:
    src: ../docker-compose.yml
    dest: '{{ app_dir }}'

- name: Copy api-py docker file
  copy:
    src: ../ranking_system/Dockerfile
    dest: '{{ app_dir }}/ranking_system/'

- name: Copy api-py files
  copy:
    src: ../ranking_system/codebase
    dest: '{{ app_dir }}/ranking_system/'

- name: Ensure cluster directory exists
  action: file path={{ app_dir }}/ranking_system{{ cluster_path }} state=directory

- name: Ensure dataset directory exists
  action: file path={{ app_dir }}/ranking_system{{ dataset_path }} state=directory

- name: Ensure tmp directory exists
  action: file path={{ app_dir }}/ranking_system{{ temp_path }} state=directory

- name: Copy api-js docker file
  copy:
    src: ../vk_interaction_obj_rec/Dockerfile
    dest: '{{ app_dir }}/vk_interaction_obj_rec/'

- name: Copy api-js token file
  copy:
    src: ../vk_interaction_obj_rec/.env
    dest: '{{ app_dir }}/vk_interaction_obj_rec/'
- name: Copy api-js files
  copy:
    src: ../vk_interaction_obj_rec/codebase
    dest: '{{ app_dir }}/vk_interaction_obj_rec/'

- name: start docker
  docker_service:
    build: yes
    project_src: '{{ app_dir }}'
    state: present