mongourl: 'mongodb://root:rootPassXXX@mongo-db:27017/admin'
database: 'lostpets'
collection: 'dataset'
collection_new: 'datastore'
image_url: 'https://sun9-44.userapi.com/c635104/v635104532/56199/xUZvuTiE0pA.jpg'
cluster_path: '../cluster/knn.joblib.pkl'
dataset_path: '../dataset/'
temp_path: '../tmpdata/'

test:
  api_url: 'http://127.0.0.1:5000'
  mongourl: 'mongodb://root:rootPassXXX@35.228.60.57:27017/admin'