---
# tasks file for env



- name: Install a containerd .deb package from the internet.
  apt:
    deb: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/containerd.io_1.2.5-1_amd64.deb
- name: Install a Docker-cli-ce .deb package from the internet.
  apt:
    deb: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce-cli_18.09.5~3-0~debian-stretch_amd64.deb

- name: Install a Docker-ce .deb package from the internet.
  apt:
    deb: https://download.docker.com/linux/debian/dists/stretch/pool/stable/amd64/docker-ce_18.09.5~3-0~debian-stretch_amd64.deb

- name: Enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install pip3
  apt:
    name: python3-pip
    state: latest

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Install docker for py
  pip:
    name: docker