---
# tasks file for env

- name: Install dnf plugins
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
    state: latest

- name: Add repo
  shell: "sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo"

- name: Install docker
  ansible.builtin.dnf:
    state: latest
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install pip3
  dnf:
    name: python3-pip
    state: latest

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Install docker for py
  pip:
    name: docker